Repository Radio-Spectrum/SHARC, pull requests merged in 2024-08, with the labels that each got.

#44 NTN Topology Unit Test [Issue 26]
  sharc/topology/topology_ntn.py
  tests/test_topology_ntn.py
Labels: help wanted

#42 Unit tests for LEO (1200Km and 600Km) satellites [Issue 33].
  tests/Plots_observed/1200Km and 600Km elevation plots.png
  tests/Plots_observed/1200Km footprint.png
  tests/Plots_observed/600Km footprint.png
  tests/test_footprint.py
  tests/test_footprint_LEO (Legacy).py
  tests/test_footprint_legacy.py
Labels: good first issue, help wanted

#12 Improvement: propagation refactoring
  sharc/input/parameters.ini
  sharc/parameters/parameters_eess_passive.py
  sharc/parameters/parameters_fss_es.py
  sharc/parameters/parameters_fss_ss.py
  sharc/parameters/parameters_general.py
  sharc/parameters/parameters_haps.py
  sharc/parameters/parameters_ras.py
  sharc/parameters/parameters_rns.py
  sharc/propagation/propagation.py
  sharc/propagation/propagation_abg.py
  sharc/propagation/propagation_clear_air_452.py
  sharc/propagation/propagation_clutter_loss.py
  sharc/propagation/propagation_factory.py
  sharc/propagation/propagation_free_space.py
  sharc/propagation/propagation_hdfss.py
  sharc/propagation/propagation_hdfss_roof_top.py
  sharc/propagation/propagation_indoor.py
  sharc/propagation/propagation_p619.py
  sharc/propagation/propagation_sat_simple.py
  sharc/propagation/propagation_ter_simple.py
  sharc/propagation/propagation_tvro.py
  sharc/propagation/propagation_uma.py
  sharc/propagation/propagation_umi.py
  sharc/propagation/scintillation.py
  sharc/simulation.py
  sharc/simulation_downlink.py
  sharc/simulation_uplink.py
  sharc/station_factory.py
  sharc/station_manager.py
  tests/main.py
  tests/test_adjacent_channel.py
  tests/test_simulation_downlink.py
  tests/test_simulation_downlink_haps.py
  tests/test_simulation_downlink_tvro.py
  tests/test_simulation_uplink.py
Labels: enhancement
